### ISSUE TITLE
Need update to subdependencies bootstrap and jquery

### ISSUE THREAD

**Issue by kwonjoseph** [visjs/vis-network#10]
Hi visjs team,

I have gotten to this page from being referred to by @mojoaxel  who I found through your github page. I am filing an issue to update some of vis-network’s subdependencies.  The ones in particular are bootstrap and jquery.  Our risk team here at paypal has deemed these versions of the libraries you guys are utilizing to be potentially vulnerable and are not allowing them to pass the ECI check scripts.  Please advise on how I can raise the version of bootstrap to 3.4.1 or higher and having at least the latest version of jquery 1.x.x or 2.x.x.  Please and thank you for your time.  Please see the attached screenshot for reference.  Thanks again!
browser: chrome(not a frontend issue so not relevant in my opinion)
This screenshot reveals visjs(4.21.0) but when I tried it with vis-network(5.0.0) it was utilizing the same versions of these libraries.
<img width="1215" alt="Screen Shot 2019-07-23 at 8 31 24 PM" src="https://user-images.githubusercontent.com/26152604/61846592-88fcbd80-ae5c-11e9-81fe-30384a1dc188.png">
 
Best Regards,

Joseph Kwon

**Comment by mojoaxel** [comment]
I looked into it. Bootstrap and jQuery are no dependencies, but are used in the docs.
We should replace them with CDN links.

**Comment by kwonjoseph** [comment]
sorry, if possible may you clarify what exactly I would need to do on my end to achieve this? please and thank you

**Comment by mojoaxel** [comment]
@kwonjoseph I'll provide a fix shortly.

**Comment by mojoaxel** [comment]
@kwonjoseph Until this is "fixed" You can maybe just manually delete the folder:
- "node_modules/vis-network/docs/"
- "node_modules/hammerjs/tests/unit/"

**Comment by mojoaxel** [comment]
The problem is that we have static assets (e.g. jquery.min.js) that are used by the docs.

I see two ways to approach this:
1. update boostrap, jquery and other possible assets to up-to-date versions.
2. remove static assets in favor of cdn links.

I prefer removing these static assets from vis-network (option 2). But this has the problem that the docs can not be viewed anymore if the CDN has problems or the user has no access to the CDN (China?).

What do you guys think? 1 or 2 ?

**Comment by mojoaxel** [comment]
There is another problem: [hammer.js](https://github.com/hammerjs/hammer.js) has removed jquery as a test dependency but has not released a new version (since 2016). If we want to fix this problem too we would need to fork hammer.js and provide our own custom build (e.g. vis-hammer) or depend on an unreleased version via a direct github-dependency.

**Comment by kwonjoseph** [comment]
so the ECI does its own npm install before running these tests I don't think the temporary solution you have suggested would resolve my issue.  Thank you for working on this issue!

**Comment by mojoaxel** [comment]
@kwonjoseph Have you talked to the ECI people. All this dependencies are in docs or tests. These libraries do not get bundled or delivered in any way. This is clearly a problem with there tools!

We easily could fix the "problems" in vis-network but not in hammerjs.

**Comment by mojoaxel** [comment]
`propagating-hammerjs` also should use hammerjs@2.0.8: https://github.com/josdejong/propagating-hammerjs/pull/11

**Comment by mojoaxel** [comment]
@kwonjoseph your issues should be fixed. Keep you eyes up for the upcoming major release!

**Comment by mojoaxel** [comment]
@kwonjoseph Thanks for opening this issue. We are happy that it could be resolved! Working on these issues takes a lot of time. Please consider [supporting](https://opencollective.com/visjs/contribute) further maintenance and development!

**Comment by kwonjoseph** [comment]
no problem thank you for helping me with this issue.  I appreciated the support.
