### ISSUE TITLE
Allow event handlers to be async

### ISSUE THREAD

**Issue by aryzing** [visjs/vis-network#1282]
Currently, all event handlers are sync and return `void`, which makes using async operations possible only using the `then` and `catch` methods (or other techniques like creating and calling an async function that's called within the sync callback).

Can we change the types to allow for async callbacks? What are the drawbacks?

**Comment by Thomaash** [comment]
Hi @aryzing,

you can use async callbacks, they just won't be awaited. Changing the types would be misleading as the return value is always ignored (that's what the void means).

I'm not sure what's your use case or problem here.

**Comment by aryzing** [comment]
>  the return value is always ignored (that's what the void means).

Sure, and can't the same be true with

```ts
type Callback = void | Promise<void>
```

?

There is still no expectation of the lib awaiting the callback or handling any return value.

**Comment by aryzing** [comment]
Fair enough, thanks for the correction, and aplogies for the incorrect type definition. 

Regarding the types, here too you're right: an async func can be assigned sync one with void callback, I was coding fast and failed to realize the error was being thrown by the linter and not the type system,

```
Promise returned in function argument where a void return was expected. (@typescript-eslint/no-misused-promises)
```

Seems the linter here is on your side too, in that it feels weird to assign an async func to a sync one when an async one is not expected or isn't used for anything. And I guess that's where I'm going: since there's no impact on vis-network whether the callback is sync or async, but there is impact as far as correctness goes, then what's stopping us form explicitly allowing it?

**Comment by Thomaash** [comment]
> then what's stopping us form explicitly allowing it?

Because it makes no sense to require a return value (even if optional) that will be ignored. It would be confusing to accept a promise but then not await it. I'm simply not going to change the types in a way that makes no sense because of your linting rules. Which, by the way, are right; what you're doing there isn't very good use of promises. What if your promise rejects? You say you're contacting the server, that may fail and Vis Network is not going to solve this for you in any way (it won't even know that it failed).

PS: Write your code in a way that explicitly states what's gonna happen (e.g. throw the promise away with `void`)
```typescript
network.on(
  "anyEvent",
  (params): void =>
    void (async (): Promise<void> => {
      await whatEver;
    })()
);
```
or reconfigure your linter so that it doesn't interfere with your practises.
