### ISSUE TITLE
Vis.js Hierarchical visualization network algorithm changed?

### ISSUE THREAD

**Issue by jmmccota** [visjs/vis-network#176]
Until Vis.js-Network version 6.0.0, hierarchical like a tree with a desired form to me, but when updated to Version 6.1.1, the visualization change, there is a workaround?

I want to work with newest version

I've tried various parameters changes, like change hierarchical.sortMethod between directed and hubsize, but without success.

I made these two examples bellow to explain the issue

The desired form:

[1] https://stackblitz.com/edit/react-nvk3zw?file=Arvore.jsx

The same visualization with new version:

[2] https://stackblitz.com/edit/react-fmffgx?file=Arvore.jsx

I expect some solution to use Vis.js-Network version 6.1.1, to obtain the same result as this visualization #[1]

-----

Originally asked on [StackOverflow](https://stackoverflow.com/q/58469546/932797)

**Comment by Thomaash** [comment]
Hi @jmmccota,

there was a change to the layout because the original layout under certain not so rare conditions would feature edges pointing upwards (something that can't happen in a valid hierarchy). What you see is a result of that because the layout is now built from the leaves to the root instead of root to leaves.

I'll have a look to see if an option could be added to push everything as close to the root as possible.

**Comment by Thomaash** [comment]
I implemented `shakeTowards` option which, if set to `roots`, allows you to get the layout you want. You can use https://thomaash.github.io/cdn/vis-network.1e941e89c1049db05516e82ceb305130.js or build #177 yourself. Could you test it, please?

**Comment by jmmccota** [comment]
It's looks very nice, thanks @Thomaash 

I'll wait the next build/version.
