### ISSUE TITLE
Question: Node z-indexing

### ISSUE THREAD

**Issue by Tyler-Maclachlan** [visjs/vis-network#226]
Hi guys,

I'm wondering if it would be possible to have a sort of z-indexing for nodes, especially on hover. Dragging already seems to have some of this implemented.

Labels especially get 'hidden' behind other labels, and I'd like the node I'm hovering's label to be on top.

This also creates weird interactions when using custom functions on the hover, drag and blur events.

Example:
Node hover increases its size and shows its label.
Node blur sets size back to default and hides label

Dragging a node over another node sometimes blurs the node you are dragging and hovers the node behind it. (I assume this is dependant on the order they are in the nodes array or are rendered in)

**Comment by Thomaash** [comment]
Hi @Tyler-Maclachlan,

this seems like three separate issues to me:
1. setting custom z-index,
1. nodes jumping in front of and behind each other (I can confirm this),
1. glitches during node dragging (I can't reproduce this).

If I'm right could you split this into three issues so that we can track each one independently, please?

**Comment by Tyler-Maclachlan** [comment]
Hi @Thomaash 

I don't think this needs a public custom z-index method, I just think the renderer needs to take into account which node (if any) is being dragged/hovered/selected and render that last - which will give the z-index effect needed to fix this.
