### ISSUE TITLE
Edge events broken ?

### ISSUE THREAD

**Issue by Rico66100** [visjs/vis-network#228]
Events on edge seems to be broken, since 6.1.2.

https://visjs.github.io/vis-network/examples/network/events/interactionEvents.html

My console: 
![Screenshot from 2019-11-12 14-41-25](https://user-images.githubusercontent.com/51325367/68676697-d5c6ea00-055a-11ea-87c8-d094ba073c19.png)

**Comment by Rico66100** [comment]
Works fine with 6.2.0

**Comment by Thomaash** [comment]
Hi @Rico66100,

more info about triggering this would be appreciated. However after some fiddling around I found out a way to trigger this.

It happens when an edge is reconnected. Just as the end of the edge is dropped onto a node an error is thrown and the edge is forever stuck in there. It's possible to redrop the edge but that throws just another instance of the same error.

PS: If there are more ways how to trigger this feel free to share it with us.

**Comment by Thomaash** [comment]
> Hmm, this class has a beautiful property that starts with an underscore. Let's use it!

Sometimes I really wonder what were the people thinking? I understand when people do this if there's no other way but why here? Why would anyone chose `._data[id]` (private, undocumented) over `.get(id)` (public, part of the documented API)?

PS: For those who don't know in JavaScript convetions underscore means it's private and should never be accessed from the outside as it can change or disappear at any moment without any warning.
PPS: This was introduced by person whose bio says "The Software Barbarian" :smile:.

**Comment by Thomaash** [comment]
There are several places where this is used so many more things should be broken. I'm actually surprised it works at all.

**Comment by Rico66100** [comment]
@Thomaash : Sorry, to trigger this, I select an edge then 'Edit Edge'. Select on of the drag/drop circle and just drop it on a node.
