### ISSUE TITLE
Change Keywords? (like size)

### ISSUE THREAD

**Issue by qohelet** [visjs/vis-network#234]
Hi,
for our graphs we already have quite a lot of values included in each node.
I'd prefer to have the design-related part (used for visjs) in the code visually more separated from the data related parts.
Let's say I'd like to have the attribute-keys "size", "id", "value" or "color" written to be with a prefix. 
Like "vis_size", "vis_id", "vis_value" or "vis_color". 

Is that actually possible?
Thank you

**Comment by Thomaash** [comment]
Hi @qohelet,

I'm sorry to disappoint you but to put it simply the answer is no. This, although possible, would require massive overhaul of the entire library and would break everything that depends on it.

I suggest you keep all Vis related values under dedicated vis property and supply that to Vis Network or go the other way around and have some payload property containing all nonVis data to keep them separated.

**Comment by Thomaash** [comment]
Hi @qohelet again,

I was thinking about replacing one flawed and inflexible feature of data sets with an alternative and your issue came to my mind. There's no code yet but the idea is to synchronize two data sets and add some processing in between:
```typescript
interface DataSync<SourceItem, SourceIdProp, TargetItem, TargetIdProp> {
  constructor({
    source,
    map,
    target
  }: {
    source: DataInterface<SourceItem, SourceIdProp>;
    filter(item: SourceItem): boolean;
    map(item: SourceItem): TargetItem;
    target: DataSet<TargetItem, TargetIdProp>;
  });

  syncing: boolean;
  start(): void;
  stop(): void;
}
```
This would allow you to have a data set with prop names (and data types, formats, structures etc.) of your choosing and have it automatically mapped in real time to a different data set used in Vis Network with the required names. Do you think this would also be an acceptable solution to your problem?
