### ISSUE TITLE
MSIE webbrowser component not working

### ISSUE THREAD

**Issue by joyholdgod** [visjs/vis-network#249]
Dear visjs

I'm a developer in Korea.
I'm not good at English.
I need your help.
I'm stucked developing network diagram.

It works in ordinay web browser. IE11 also works greatly.
But the problem is when I use Webbrowser component that supported Microsoft.

I tested vis in "webbrowser component".
The problem is Event.
mouse drag, click,selectnode are not working. But scrolling, hovernode works.
It gives me same result when I use example from visjs.

But cytoscape is working in web and webbrowser component.

And I can not get the node id in hovernode at webbrowser component.

I have to develope flow diagram using not visjs.But It is so sad to me. My brain is sick.
I want to use visjs.

Is there any solution?

My project closes in December.
Please help me.
Thank you.

**Comment by Thomaash** [comment]
Hi @joyholdgod,

this sounds a bit like an issue that appeared in 6.1.2 and should be resolved since 6.4.3, I'm not 100 % sure though. Could you test it with 6.4.3 explicitly and if the issue still persist post a screenshot with console output?

Thanks.

PS: I have never worked with webbrowser components. Could you maybe provide an MWE that I could use for testing?

**Comment by joyholdgod** [comment]
I'm not famillier github.
I tested 6.4.3.

1. download vis-neteork-6.4.3.zip
2. unzip the zip file.
2. double click "examples/network/basicUsage.html"
3. nodes and edges not displayed
3. edited source basicUsage.html
../../standalone/umd/vis-neteork.min.js
=> edit => ./vis.js
4. inserted file vis.js in same directory
( vis.js version is 4.21.0 )
5. opend the file in webbrowser component.
6. nodes, edges is displayed. Buy dragging is not worked...

In my opinion, vis.js is occure problem. or other.
Shoud I say to vis data of github ?

I cant mail or file to out to others
It is not my ability.
The company that I work is secure reason.
Your profile picture is handsome.
Thank you.

**Comment by joyholdgod** [comment]
Dear Thomaash
I mailed to you with programm.

Thank you.

**Comment by Thomaash** [comment]
So I finally got to properly investigate this and the result is following: MSIE webbrowser component doesn't dispatch pointer* events which we listen to. However it dispatches mouse* events which theoretically could be used instead. A little complication here is that we use Hammer.js to handle these things so it has to be fixed there. I therefore suggest that you open an issue on https://github.com/naver/hammer.js/issues/new and after it's solved and released there we can update Hammer.js here and everything will hopefully work just fine.

**Comment by joyholdgod** [comment]
I opend the issue!~
Thank you!!!

**Comment by joyholdgod** [comment]
Dear Thomassh 
I got the message from Hammer.js below.

https://github.com/naver/hammer.js/issues/23#issuecomment-557969579

---------------
Hello, @joyholdgod!
If the pointer events are the problem here, there's an option to disable it in hammer.js.
That can be done by giving an option with inputClass with value TouchMouseInput when creating a Manager instance.

import { Manager, TouchMouseInput } from "@naver/hammer.js";

// Suppose you have this version info..
if (IE_VERSION <= 10) {
  const manager = new Manager(someEl, {
    inputClass: TouchMouseInput
  });
}
If this won't work, please leave any example that can reproduce this issue so we can fix that :)

Thank you!~

**Comment by Thomaash** [comment]
So the solution from naver/hammer.js#23 works for the events but that's just a small part of it. Many other parts of the library don't work. The problem is that that thing is IE7. Adding compatibility tag or editing registers don't change anything. It's simply IE7. It even claims to be IE7 in it's user agent. I even checked if globals like `window.JSON` introduced in IE8 exist and they don't.

I'm sorry that I didn't help you but the oldest browser we support is IE11 (full list on https://browserl.ist/?q=%3E+0.1%25+or+not+dead). I suggest that you switch to more modern component that is based on something like Chromium or at least IE11/Edge.
