### ISSUE TITLE
No Zoom configuration or option to alter default behaviour

### ISSUE THREAD

**Issue by jbu4github** [visjs/vis-network#298]
Can we add some parameter for zoom animation by default? Its really sharp and I cant find a way to add animation to it.

Alternatively expose the original mousewheel event in the listener so we can cancel it and use the exposed zoom methods with animation (moveTo)

Alternatively not have the "user can zoom" boolean prevent programmatic zoom with moveTo.

Any one of these would be absolutely fine. If this can be done somehow and I have missed it also please let me know.

Thanks in advance :)

**Comment by jbu4github** [comment]
A maximum zoom would also be nice.
I feel like a lot could be achieved really quickly with some work on zoom. 💃

**Comment by Thomaash** [comment]
Hi @jbu4github,

to put it shortly:
- We can add optional animation or limits. We don't really have the people to do so though as there are more pressing issues right now I'm working on (I'm practically the only one working on this library at the moment). If you have the time to contribute that would be really appreciated.
- We can't expose the raw event because there are multiple ways you can zoom (mouse wheel, pan, button). It would be mess. There is a zoom event already that can be used and contains everything important (what else do you need?)
- Even if zooming by user is disabled by `options: { interaction: { zoomView: false } }` it is still possible to use `moveTo()` to zoom. I think you should be able to implement all the features you want by simply disabling zoom and listening for the events on your own and then handling them using `moveTo()`.

**Comment by jbu4github** [comment]
Oh I apologise, it is indeed possible to use `moveTo()` with `zoomView: false`.
All I have now is the problem of implementing my own zoom with the wheel. Which would be a lot easier if the zoom handler still raised events while `zoomView: false`.

Ill have a go and raise a PR if nothing else goes my way :)

Thanks!

**Comment by jyzbamboo** [comment]
> Hi @jbu4github,
> 
> to put it shortly:
> 
> * We can add optional animation or limits. We don't really have the people to do so though as there are more pressing issues right now I'm working on (I'm practically the only one working on this library at the moment). If you have the time to contribute that would be really appreciated.
> * We can't expose the raw event because there are multiple ways you can zoom (mouse wheel, pan, button). It would be mess. There is a zoom event already that can be used and contains everything important (what else do you need?)
> * Even if zooming by user is disabled by `options: { interaction: { zoomView: false } }` it is still possible to use `moveTo()` to zoom. I think you should be able to implement all the features you want by simply disabling zoom and listening for the events on your own and then handling them using `moveTo()`.

Thankyou

**Comment by codergautam** [comment]
I was able to do with a workaround, pls thumbs up if it helps

```
let lastPosition = null;

    network.on("zoom", function (params) {
      if (params.scale < 0.5) { // adjust this value according to your requirement
        network.moveTo({
          position: lastPosition, // use the last position before zoom limit
          scale: 0.5 // this scale prevents zooming out beyond the desired limit
        });
      } else {
        // store the current position as the last position before zoom limit
        lastPosition = network.getViewPosition();
      }
    });
```
