### ISSUE TITLE
WidthConstraints and HeightConstraints for the node is not updating using setOption()

### ISSUE THREAD

**Issue by abhinpai** [visjs/vis-network#337]
I am facing an issue to update the Width and the height for a node on zoom. 

Initially node shape will be Circle and on zoom at certain value the shape of the node change into the box but width and height for a node is not updating only the shape is updating 

Here is the code sample 

    network.on('zoom', function(params) {
        if (params.direction == '+' && params.scale > 0.8) {
          changeShape(params.scale);
        }
        if (params.direction == '-' && params.scale < 0.8) {
          resetShape(params.scale);
        }
      });

     function changeShape(scale) {
        var options = {
          nodes: {
            widthConstraint: 1000,
            heightConstraint: 100,
            shape: 'box'
          }
        };
        network.setOptions(options);
        network.setOptions({ physics: { stabilization: { fit: false } } });
        network.stabilize();
      }

      function resetShape(scale) {
        network.setOptions({
          nodes: {
            shape: 'circle',
            borderWidth: 2
          }
        });
      }

**Comment by Thomaash** [comment]
Hi @abhinpai,

the problem is that `changeShape` sets the constraints to 1 000 and 100. That's it. Nothing else happens to it. It just stays 1 000 and 100 forever.

Another problem is that even if you would have changed it it would still be ignored and I have no idea how this works. The way we handle options is such a terrible mess that I just can't find anything in it.

PS: Running `nodes.updateOnly(nodes.get())` will update everything including the constraints assuming that `nodes` is a DataSet of nodes you passed to the Network constructor.

**Comment by abhinpai** [comment]
Thanx @Thomaash for the quick reply.

Do i need to update the node options one by one in-order to change the size of the node on zoom ?

**Comment by Thomaash** [comment]
Sadly it seems so. The constraint is simply never updated. The trick is actually in setting the label to the same value it was before which forces the label and therefore the constraints on it to be reevaluated.

**Comment by Thomaash** [comment]
Hi @abhinpai,

this will be fixed in 7.0.1 which is already in the process of being released.

PS: The breaking change is in layout seeding. Unless you depend on particular layout being created for particular seed you can safely upgrade.
