### ISSUE TITLE
closeCluster() ?

### ISSUE THREAD

**Issue by grekier** [visjs/vis-network#354]
Hi.

First thanks for the great lib. Loving it.

I was wondering if there was a possibility to close a cluster onClick? As of now, we use the openCluster to "expand" it but it would be nice to "revert" the change in some way.

Is it possible? If so, how? If not, could we add a feature request for it?

Thanks.

**Comment by Thomaash** [comment]
Hi @grekier,

the naming here is a bit confusing. The method `.cluster()` creates a cluster and `.openCluster()` releases the clustered nodes and edges from the cluster and then disposes of it. There's no way to close it because it no longer exists.

To achieve what you want you can save the ids of the clustered nodes before calling `.openCluster()` and then use `joinCondition` in `.cluster()` to recreate the cluster with the same nodes.

**Comment by grekier** [comment]
Thanks @Thomaash 
I tried what you suggested and recreated the cluster based on the id from the click event and it works nicely.

**Comment by Thomaash** [comment]
You're welcome.
