### ISSUE TITLE
Network nodes not auto centered when using Bootstrap modal .fade class

### ISSUE THREAD

**Issue by askuri** [visjs/vis-network#531]
When showing a Network in a Bootstrap modal and it has the .fade css class, the nodes are not centred automatically and one always has to adjust it.

**Actual Behaviour**: I've created an (example)[https://jsbin.com/xisegurida/edit?html,output]. Where the modal is in the HTML code, I have marked the location where to add or remove the .fade class, so you can try yourself how it renders.

**Expected behaviour**: vis.js is able to automatically center the nodes, even when the bootstrap fade class.

**System Information**: Firefox 74.0 on Kubuntu 19.10

**Comment by Thomaash** [comment]
From my fiddling with it, it seems that the element you're rendering into has zero size when you create the network. Vis Network has no idea about Bootstrap so it fits right away and when Bootstrap decides to resize it, it's already fitted and you end up with graph that is not centered.

I'm sorry but you'll have to fit manually based on some Bootsrap events or so because if we fitted on resize many people would come complaining about that and adding and maintaining special case support for arbitrary libraries is just way outside of this project's resources (unless, of course, you plan to do something about that and if you do than many thanks).

PS: You can reopen if I missed something, you have more info etc.
