### ISSUE TITLE
the node position

### ISSUE THREAD

**Issue by Sky-Young** [visjs/vis-network#568]
I met a problem，when i set one node position fixed ( like {x: 0, y: 0}).
But it's still in the center of the canvas.
How do i make it at the specified position on the canvas.

![image](https://user-images.githubusercontent.com/13446611/77303825-89708f80-6d2e-11ea-9baa-96947ecc1c7c.png)

![image](https://user-images.githubusercontent.com/13446611/77303420-e6b81100-6d2d-11ea-976a-508e8adbccc7.png)

![image](https://user-images.githubusercontent.com/13446611/77303748-6cd45780-6d2e-11ea-8063-df3335b18cdb.png)

**Comment by Thomaash** [comment]
Vis Network automatically fits the content into the canvas on start up so that there's nothing out of view (the node is where you wan't it to be, the viewport isn't). Check the `moveTo` from https://visjs.github.io/vis-network/docs/network/#methodViewport part of the docs if you want to set something custom (it won't be changed later on, you can set it once and be done with it if that's what you want).

PS: I'm not sure if this is helpful or you already know it, but DOM coordinates and canvas coordinates are not the same thing (due to the fact that you can move the viewport and zoom it). You have to convert using `DOMToCanvas` and `canvasToDOM` methods to get a node to a specific position in the “DOM”.

**Comment by Sky-Young** [comment]
> Vis Network automatically fits the content into the canvas on start up so that there's nothing out of view (the node is where you wan't it to be, the viewport isn't). Check the `moveTo` from https://visjs.github.io/vis-network/docs/network/#methodViewport part of the docs if you want to set something custom (it won't be changed later on, you can set it once and be done with it if that's what you want).
> 
> PS: I'm not sure if this is helpful or you already know it, but DOM coordinates and canvas coordinates are not the same thing (due to the fact that you can move the viewport and zoom it). You have to convert using `DOMToCanvas` and `canvasToDOM` methods to get a node to a specific position in the “DOM”.

ok，thank you very much!
