### ISSUE TITLE
about Chinese translation

### ISSUE THREAD

**Issue by aimeiyijia** [visjs/vis-network#778]
vis-network is a great library.
    so I made a Chinese translation (first version), although there are some translation errors, but help me put it into awesome-visjs or other, let us improve it together:
     [this is the link](http://www.qust.vip/core/frontend-tools/)
     [github link](https://github.com/aimeiyijia/ame/tree/master/docs/数据可视化/00.vis-network中文文档) 。
     I will continue to update it, thank you!

**Comment by Thomaash** [comment]
Hi @aimeiyijia,

I don't understand a word but otherwise it looks great. I see your using Vuepress, I would actually like to have all the docs in Vuepress. Would you have the time to help with that? We could then have all the docs in the same style here which would be great. I think it would also make maintaining it much easier. Otherwise we can just link your docs from here.

Thanks for your work either way.

**Comment by Thomaash** [comment]
I meant that I don't understand a word in Chinese, otherwise I understand.

**Comment by aimeiyijia** [comment]
@Thomaash  Can you put the Chinese document in a place where others can find it？

**Comment by Thomaash** [comment]
Sure, I'll put a link into the official docs. What flag should I use?

**Comment by aimeiyijia** [comment]
Whatever you want
