### ISSUE TITLE
vis-data is a dependency not a peerDependency

### ISSUE THREAD

**Issue by sternenseemann** [visjs/vis-network#884]
vis-network can be used without using vis-data in your js code, i. e. use arrays instead of `DataSet`s.

However, you have to add vis-data to your `package.json`, as vis-network calls `require()` internally to get vis-data.

As the [npm documentation states](https://docs.npmjs.com/files/package.json#peerdependencies):

>In some cases, you want to express the compatibility of your package with a host tool or library, while not necessarily doing a require of this host. This is usually referred to as a plugin. Notably, your module may be exposing a specific interface, expected and specified by the host documentation.

If you use `browserify` for example, building your javascript will straight up fail if you don't add vis-data to your `package.json`, which indicates it is not in fact a peer dependency.

**Comment by Thomaash** [comment]
Vis Data has to be a peer dependency otherwise you couldn't use e.g. Vis Network together with Vis Timeline (each would have Vis Data of it's own and you would have a third one, this arrangement just doesn't work). If you don't want to deal with these things and are okay with limiting yourself to Vis Network only then `import { DataSet, Network } from "vis-network/standalone";`.

PS: I know it's quite confusing and yes, we should figure out a better solution (suggestions are welcome).

**Comment by sternenseemann** [comment]
My point is not about sharing `DataSet` in my application, whatever code when using vis-network and vis-timeline simuntaneously, but that vis-network won't work without it.

I have a project with only imports

```js
import { Network } from 'vis-network';
```

I compile it using `browserify source/main.js -t babelify -d -o dist/main.js`.

If I don't add `vis-data` to my `package.json` as dependency it won't compile even though I don't use `vis-data` myself. This is becaus `vis-network` imports `vis-data` somewhere, i. e. depends on it.

**Comment by Thomaash** [comment]
Yeah, it does depend on it, that's why it's a peer dependency. Peer dependencies are not optional, you have to have them installed to use given package (npm will output warnings if you don't and older versions even automatically installed them just like regular dependencies). Also there is nowhere said that peer dependencies can't be imported, it just says they don't have to. Otherwise they would be called something like compatibilities (i.e. you can use this with that) not dependencies (i.e. you need this to use that).

I get your point, but adding Vis Data as a dependency would break many projects, having it as a peer dependency is just annoying (the better option here).
