### ISSUE TITLE
Expanded children of cluster node have same coordinates when physics are disabled

### ISSUE THREAD

**Issue by charleshtrenholm** [visjs/vis-network#937]
Hello and thank you for maintaining such a great library. I have found VisJS and its documentation to be incredibly intuitive and easy to use. 

I am however stuck on an issue regarding clustered nodes. I have a network of items that will have rough initial x and y coordinates for some nodes. I use physics to push the nodes without x and y coordinates apart from each other and then disable physics on the stabilizationIterationsDone event.

Based on the data from the server, I create a list of nodes that I want to have clustered with their children. The problem I am running into is that even when the children are provided X and Y coordinates, they all end up in the same place on top of the expanded "parent" node. 

It appears that when I leave physics enabled, they will force each other apart, but when they are turned off they all stay on top of the parent node and the x and y values appear to be ignored. Is there any way I can specify the position of nodes after a cluster is expanded without enabling physics? I have tried turning physics on for only the cluster expand click handler, but the nodes just disappear when I do that.

Thanks for your help! Here is a [link](https://codepen.io/Charlietrenholm/pen/KKzpooX?editors=1111) on code pen of a minimal replication of the issue

**Comment by Thomaash** [comment]
Hi @charleshtrenholm,

this is actually intentional and documented behavior, they are supposed to explode from the cluster, because the user could move the cluster (and the clustered nodes with it) anywhere. If the original positions were restored, then the unclustered nodes could reappear in very unexpected places, maybe even out of screen.

However the original positions are remembered for use cases like yours and you can simply achieve what you want by supplying custom `releaseFunction` that simply returns the original positions:
```javascript
network.openCluster(clusterId, {
  releaseFunction: (_, positions) => positions,
});
```
